# Generated by Django 3.1 on 2020-08-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20200805_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descrption',
            new_name='description',
        ),
    ]
